version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: translation_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: translation_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: translation_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: translation_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
    depends_on:
      - app

volumes:
  db_data: